### ISSUE TITLE
About cuda

### ISSUE THREAD

**Issue by SongFGH** [rgcottrell/pytorch-human-performance-gec#1]
Hi, I have a probelm:RuntimeError: CuDNN error: CUDNN_STATUS_SUCCESS.
And, you write this sentence:If RuntimeError: CuDNN error: CUDNN_STATUS_SUCCESS occurs during training, try install pytorch with CUDA 9.2 using conda instead of using default CUDA 9.0.
Can you explain this sentence? I usually install pytorch using pip

**Comment by tianfeichen** [comment]
We used CUDA 9.2 and never tried it on CUDA 9.
