### ISSUE TITLE
fairseq 

### ISSUE THREAD

**Issue by xiaoshengjun** [rgcottrell/pytorch-human-performance-gec#6]
hi, which version 'fairseq' are you used, when I run genetate.py, 
for example:
      sh generate_lang8.sh,
Traceback (most recent call last):
  File "./generate.py", line 238, in <module>
    main(args)
  File "./generate.py", line 89, in main
    sampling=args.sampling, sampling_topk=args.sampling_topk, sampling_temperature=args.sampling_temperature,
AttributeError: 'Namespace' object has no attribute 'sampling_temperature'.

Could you share the fairseq you used, case I only find the latest version in github, thank you very much.

**Comment by tianfeichen** [comment]
When we created the project we have to clone / modify a few files so they are included as git submodule.

There has been lots of change in fairseq. You should grab an older version of fairseq committed / tagged around Oct 4, 2018.
